[workspace]
authors = ["Gengyao Qiu <aylwingun@outlook.com>"]
channels = ["conda-forge"]
name = "matbench"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pytorch-gpu = "*"
pymatgen = "==2025.6.14"
helix = ">=25.7.1,<26"
ipykernel = ">=7.1.0,<8"
ase = ">=3.27.0,<4"
wandb = ">=0.23.1,<0.24"
pudb = ">=2025.1.5,<2026"
cython = ">=3.2.4,<4"
[system-requirements]
libc = {family = "glibc", version="2.28"}
cuda = "12.6"
[pypi-dependencies]
taichi = "==1.6.0"
torch-geometric = ">=2.7.0, <3"
ultraimport = ">=0.1.0, <0.2"
